---
- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Install container runtime
  hosts: all
  become: true
  vars:
    # ! CUSTOMIZE
    cri_var_cri: "docker"
  roles:
    - cri
