---
# === MySQL Root Password ===
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  root-password: "cm9vdHBhc3N3b3Jk" # echo -n 'rootpassword' | base64
