---
- name: Apply Weave Net manifest
  ansible.builtin.command: "kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml"
  register: kubectl_output
  changed_when: kubectl_output.rc != 0
