---
- name: Check /etc/containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create containerd default configuration
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      containerd config default | tee /etc/containerd/config.toml
    executable: /bin/bash

- name: Configuring the systemd cgroup driver
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    insertafter: '\[plugins\."io\.containerd\.grpc\.v1\.cri"\.containerd\.runtimes\.runc\.options\]'
    line: "            SystemdCgroup = true"
    regexp: '^\s*SystemdCgroup\s*='
    state: present

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
