---
- name: Install Docker from apt
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Run and enable Docker daemon
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
