---
# === Redis Insight Deploy ===
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisinsight
  template:
    metadata:
      labels:
        app: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight
          ports:
            - containerPort: 5540
              name: http
              protocol: TCP
          # ! CUSTOMIZE: Logging ---
          env:
            - name: RI_STDOUT_LOGGER
              value: "true"
            - name: RI_LOG_LEVEL
              value: "debug"
            # ---
            # ! CUSTOMIZE: preconfigured database connections ---
            - name: RI_PRE_SETUP_DATABASES_PATH
              value: "/etc/redisinsight/connections.json"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          # ! CUSTOMIZE: preconfigured database connections
          volumeMounts:
            - name: config-connections
              mountPath: /etc/redisinsight/connections.json
              subPath: connections.json
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck/
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      # ! CUSTOMIZE: preconfigured database connections
      volumes:
        - name: config-connections
          configMap:
            name: config-connections
      # ---
