---
- name: Enable IPv4 packet forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
    reload: true
- name: Check result
  ansible.builtin.command: "sysctl net.ipv4.ip_forward"
  register: result
  changed_when: result.rc != 0
- name: Print result
  ansible.builtin.debug:
    var: result.stdout
