---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: cnd-keycloak
          imagePullPolicy: IfNotPresent
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: "bootstrap-admin"
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "qwerty"
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 9000
          args:
            - "start"
            - "--optimized"
          resources:
            requests:
              memory: "1700Mi"
              cpu: "500m"
            limits:
              memory: "2000Mi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: keycloak-config
              mountPath: /opt/keycloak/conf/keycloak.conf
              subPath: keycloak.conf
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: keycloak
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
