---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    root_url = http://localhost:3000

    [security]
    admin_user = admin
    admin_password = qwerty
