---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    root_url = http://localhost:3000

    [security]
    admin_user = admin
    admin_password = qwerty

    # Keycloak SSO setup
    [auth.generic_oauth]
    enabled = true
    name = keycloak
    allow_sign_up = true
    client_id = grafana
    client_secret = <KEYCLOAK_CLIENT_SECRET>
    scopes = openid offline_access
    email_attribute_path = email
    login_attribute_path = preffered_username
    name_attribute_path = name
    auth_url = http://<GRAFANA>/realms/<REALM>/protocol/openid-connect/auth
    token_url = http://<GRAFANA>/realms/<REALM>/protocol/openid-connect/token
    api_url = http://<GRAFANA>/realms/<REALM>/protocol/openid-connect/userinfo
    role_attribute_path = contains(roles[*], 'grafana_admin') && 'Admin' || contains(roles[*], 'grafana_editor') && 'Editor' || contains(roles[*], 'grafana_viewer') && 'Viewer'
