# === Kibana Deployment ===
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: efk-logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.4.0 # ! version must be Elasticsearch compatible (same)
          resources:
            limits:
              cpu: "1000m"
            requests:
              cpu: "100m"
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200 # Elasticsearch service
          ports:
            - containerPort: 5601
