# === RBAC: Fluentd Cluster Role ===
# Permission to read logs in cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
  - apiGroups:
      - ""
    resources: # what kind of resources
      - pods
      - namespaces
    verbs: # what to do with resources
      - get
      - list
      - watch
# === RBAC: Fluentd Cluster Role Binding ===
# Connect Service Account to Cluster Role
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: efk-logging
