---
# === Fluentd DaemonSet ===
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: efk-logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule # allow to run on master nodes
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
          env:
            # Elasticsearch connection settings
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch.efk-logging" # dns service name
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENTD_SYSTEMD_CONF
              value: disable # disable system logs

            # ! CUSTOMIZE: containerd config
            # - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
            #   value: /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[FP]) (?<log>.*)$/

          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"
          volumeMounts:
            # ! CUSTOMIZE: containerd config
            # - name: fluentd-config
            #   mountPath: /fluentd/etc/kubernetes.conf
            #   subPath: kubernetes.conf

            - name: varlog
              mountPath: /var/log
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        # ! CUSTOMIZE: containerd config
        # - name: fluentd-config
        #   configMap:
        #     name: fluentd-config
        #     items:
        #       - key: kubernetes.conf
        #         path: kubernetes.conf

        - name: varlog
          hostPath:
            path: /var/log
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
