# === Elasticsearch Headless Service ===
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: efk-logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None # headless
  ports:
    - port: 9200 # REST API port
      name: rest
    - port: 9300
      name: inter-node
