---
# === ClickHouse Server ClusterIP ===
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: clickhouse
spec:
  selector:
    app: clickhouse-server
    component: client
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000
