---
name: CI
on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install yamllint
        run: pip3 install yamllint

      - name: Lint code
        run: yamllint .
